version: '3.7'
services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=clients-ps