POST http://localhost:3005/client
Content-Type: application/json

{
    "name": "Client 1",
    "city": "City 1",
    "status": "Status 1",
    "completed": true
}

###
GET http://localhost:3005/client
Content-Type: application/json

###
PUT http://localhost:3005/update-task/087da0f0-9470-4ac4-bb5f-9ef448b8537e
Content-Type: application/json

{
  "clientId": "ba6f7471-5b2d-4242-bc89-b49a215b5eaf",
  "types": "m",
  "obs": "",
  "description": "Limpeza de placas e verificação de conexões"
}