POST http://localhost:3005/client
Content-Type: application/json

{
    "userId":"b1bbb971-1d95-431e-b73d-2e7877782920",
    "name": "Client 1",
    "city": "City 1",
    "status": "a",
    "completed": true
}


###
PUT http://localhost:3005/update-task/087da0f0-9470-4ac4-bb5f-9ef448b8537e
Content-Type: application/json

{
  "clientId": "ba6f7471-5b2d-4242-bc89-b49a215b5eaf",
  "types": "m",
  "obs": "",
  "description": "Limpeza de placas e verificação de conexões"
}


###
POST http://localhost:3005/obras/partial-completed/14355069-61e5-4ef2-87e7-67fbde2306de
Content-Type: application/json

{
  "obs": "Teste de observação" 
}